/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ImageAnalysisResult = IDL.Record({
  'authenticityVerdict' : IDL.Text,
  'explanation' : IDL.Text,
  'isFake' : IDL.Bool,
  'ocrText' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'imageKey' : IDL.Text,
  'timestamp' : Timestamp,
  'ocrVerdict' : IDL.Text,
});
export const ReviewAnalysisItem = IDL.Record({
  'explanation' : IDL.Text,
  'isFake' : IDL.Bool,
  'reviewText' : IDL.Text,
  'confidenceScore' : IDL.Nat,
});
export const UrlAnalysisResult = IDL.Record({
  'reviews' : IDL.Vec(ReviewAnalysisItem),
  'fakeCount' : IDL.Nat,
  'sourceUrl' : IDL.Text,
  'totalReviews' : IDL.Nat,
  'genuineCount' : IDL.Nat,
});
export const AnalysisResult = IDL.Record({
  'explanation' : IDL.Text,
  'isFake' : IDL.Bool,
  'confidenceScore' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnalysisId = IDL.Nat;
export const UserId = IDL.Principal;
export const AnalysisRecord = IDL.Record({
  'id' : AnalysisId,
  'userId' : UserId,
  'explanation' : IDL.Text,
  'isFake' : IDL.Bool,
  'reviewText' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const DashboardStats = IDL.Record({
  'totalAnalyses' : IDL.Nat,
  'fakeCount' : IDL.Nat,
  'recentAnalyses' : IDL.Vec(AnalysisRecord),
  'genuineCount' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const AnalysisType = IDL.Variant({
  'URL' : IDL.Null,
  'Text' : IDL.Null,
  'Image' : IDL.Null,
});
export const AnalysisRecordV2 = IDL.Record({
  'id' : AnalysisId,
  'userId' : UserId,
  'analysisType' : AnalysisType,
  'explanation' : IDL.Text,
  'isFake' : IDL.Bool,
  'reviewText' : IDL.Text,
  'sourceUrl' : IDL.Opt(IDL.Text),
  'confidenceScore' : IDL.Nat,
  'imageKey' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
});
export const DashboardStatsV2 = IDL.Record({
  'totalAnalyses' : IDL.Nat,
  'imageCount' : IDL.Nat,
  'fakeCount' : IDL.Nat,
  'recentAnalyses' : IDL.Vec(AnalysisRecordV2),
  'urlCount' : IDL.Nat,
  'textCount' : IDL.Nat,
  'genuineCount' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const PaginatedAnalyses = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(AnalysisRecord),
});
export const PaginatedAnalysesV2 = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(AnalysisRecordV2),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'analyzeImage' : IDL.Func([IDL.Text], [ImageAnalysisResult], []),
  'analyzeProductUrl' : IDL.Func([IDL.Text], [UrlAnalysisResult], []),
  'analyzeReview' : IDL.Func([IDL.Text], [AnalysisResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMyAnalyses' : IDL.Func([], [], []),
  'deleteAnalysis' : IDL.Func([AnalysisId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDashboardStatsV2' : IDL.Func([], [DashboardStatsV2], ['query']),
  'getMyAnalyses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedAnalyses],
      ['query'],
    ),
  'getMyAnalysesV2' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(AnalysisType)],
      [PaginatedAnalysesV2],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformV2' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ImageAnalysisResult = IDL.Record({
    'authenticityVerdict' : IDL.Text,
    'explanation' : IDL.Text,
    'isFake' : IDL.Bool,
    'ocrText' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'imageKey' : IDL.Text,
    'timestamp' : Timestamp,
    'ocrVerdict' : IDL.Text,
  });
  const ReviewAnalysisItem = IDL.Record({
    'explanation' : IDL.Text,
    'isFake' : IDL.Bool,
    'reviewText' : IDL.Text,
    'confidenceScore' : IDL.Nat,
  });
  const UrlAnalysisResult = IDL.Record({
    'reviews' : IDL.Vec(ReviewAnalysisItem),
    'fakeCount' : IDL.Nat,
    'sourceUrl' : IDL.Text,
    'totalReviews' : IDL.Nat,
    'genuineCount' : IDL.Nat,
  });
  const AnalysisResult = IDL.Record({
    'explanation' : IDL.Text,
    'isFake' : IDL.Bool,
    'confidenceScore' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnalysisId = IDL.Nat;
  const UserId = IDL.Principal;
  const AnalysisRecord = IDL.Record({
    'id' : AnalysisId,
    'userId' : UserId,
    'explanation' : IDL.Text,
    'isFake' : IDL.Bool,
    'reviewText' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const DashboardStats = IDL.Record({
    'totalAnalyses' : IDL.Nat,
    'fakeCount' : IDL.Nat,
    'recentAnalyses' : IDL.Vec(AnalysisRecord),
    'genuineCount' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const AnalysisType = IDL.Variant({
    'URL' : IDL.Null,
    'Text' : IDL.Null,
    'Image' : IDL.Null,
  });
  const AnalysisRecordV2 = IDL.Record({
    'id' : AnalysisId,
    'userId' : UserId,
    'analysisType' : AnalysisType,
    'explanation' : IDL.Text,
    'isFake' : IDL.Bool,
    'reviewText' : IDL.Text,
    'sourceUrl' : IDL.Opt(IDL.Text),
    'confidenceScore' : IDL.Nat,
    'imageKey' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
  });
  const DashboardStatsV2 = IDL.Record({
    'totalAnalyses' : IDL.Nat,
    'imageCount' : IDL.Nat,
    'fakeCount' : IDL.Nat,
    'recentAnalyses' : IDL.Vec(AnalysisRecordV2),
    'urlCount' : IDL.Nat,
    'textCount' : IDL.Nat,
    'genuineCount' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const PaginatedAnalyses = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(AnalysisRecord),
  });
  const PaginatedAnalysesV2 = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(AnalysisRecordV2),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'analyzeImage' : IDL.Func([IDL.Text], [ImageAnalysisResult], []),
    'analyzeProductUrl' : IDL.Func([IDL.Text], [UrlAnalysisResult], []),
    'analyzeReview' : IDL.Func([IDL.Text], [AnalysisResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMyAnalyses' : IDL.Func([], [], []),
    'deleteAnalysis' : IDL.Func([AnalysisId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDashboardStatsV2' : IDL.Func([], [DashboardStatsV2], ['query']),
    'getMyAnalyses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedAnalyses],
        ['query'],
      ),
    'getMyAnalysesV2' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(AnalysisType)],
        [PaginatedAnalysesV2],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformV2' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };