/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisId = bigint;
export interface AnalysisRecord {
  'id' : AnalysisId,
  'userId' : UserId,
  'explanation' : string,
  'isFake' : boolean,
  'reviewText' : string,
  'confidenceScore' : bigint,
  'timestamp' : Timestamp,
}
export interface AnalysisRecordV2 {
  'id' : AnalysisId,
  'userId' : UserId,
  'analysisType' : AnalysisType,
  'explanation' : string,
  'isFake' : boolean,
  'reviewText' : string,
  'sourceUrl' : [] | [string],
  'confidenceScore' : bigint,
  'imageKey' : [] | [string],
  'timestamp' : Timestamp,
}
export interface AnalysisResult {
  'explanation' : string,
  'isFake' : boolean,
  'confidenceScore' : bigint,
  'timestamp' : Timestamp,
}
export type AnalysisType = { 'URL' : null } |
  { 'Text' : null } |
  { 'Image' : null };
export interface DashboardStats {
  'totalAnalyses' : bigint,
  'fakeCount' : bigint,
  'recentAnalyses' : Array<AnalysisRecord>,
  'genuineCount' : bigint,
  'averageScore' : bigint,
}
export interface DashboardStatsV2 {
  'totalAnalyses' : bigint,
  'imageCount' : bigint,
  'fakeCount' : bigint,
  'recentAnalyses' : Array<AnalysisRecordV2>,
  'urlCount' : bigint,
  'textCount' : bigint,
  'genuineCount' : bigint,
  'averageScore' : bigint,
}
export interface ImageAnalysisResult {
  'authenticityVerdict' : string,
  'explanation' : string,
  'isFake' : boolean,
  'ocrText' : string,
  'confidenceScore' : bigint,
  'imageKey' : string,
  'timestamp' : Timestamp,
  'ocrVerdict' : string,
}
export interface PaginatedAnalyses {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<AnalysisRecord>,
}
export interface PaginatedAnalysesV2 {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<AnalysisRecordV2>,
}
export interface ReviewAnalysisItem {
  'explanation' : string,
  'isFake' : boolean,
  'reviewText' : string,
  'confidenceScore' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UrlAnalysisResult {
  'reviews' : Array<ReviewAnalysisItem>,
  'fakeCount' : bigint,
  'sourceUrl' : string,
  'totalReviews' : bigint,
  'genuineCount' : bigint,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'analyzeImage' : ActorMethod<[string], ImageAnalysisResult>,
  'analyzeProductUrl' : ActorMethod<[string], UrlAnalysisResult>,
  'analyzeReview' : ActorMethod<[string], AnalysisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMyAnalyses' : ActorMethod<[], undefined>,
  'deleteAnalysis' : ActorMethod<[AnalysisId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDashboardStatsV2' : ActorMethod<[], DashboardStatsV2>,
  'getMyAnalyses' : ActorMethod<[bigint, bigint], PaginatedAnalyses>,
  'getMyAnalysesV2' : ActorMethod<
    [bigint, bigint, [] | [AnalysisType]],
    PaginatedAnalysesV2
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'transformV2' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];