/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ImageAnalysisResult {
    authenticityVerdict: string;
    explanation: string;
    isFake: boolean;
    ocrText: string;
    confidenceScore: bigint;
    imageKey: string;
    timestamp: Timestamp;
    ocrVerdict: string;
}
export type Timestamp = bigint;
export interface UrlAnalysisResult {
    reviews: Array<ReviewAnalysisItem>;
    fakeCount: bigint;
    sourceUrl: string;
    totalReviews: bigint;
    genuineCount: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AnalysisRecordV2 {
    id: AnalysisId;
    userId: UserId;
    analysisType: AnalysisType;
    explanation: string;
    isFake: boolean;
    reviewText: string;
    sourceUrl?: string;
    confidenceScore: bigint;
    imageKey?: string;
    timestamp: Timestamp;
}
export interface DashboardStats {
    totalAnalyses: bigint;
    fakeCount: bigint;
    recentAnalyses: Array<AnalysisRecord>;
    genuineCount: bigint;
    averageScore: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface PaginatedAnalyses {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<AnalysisRecord>;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface ReviewAnalysisItem {
    explanation: string;
    isFake: boolean;
    reviewText: string;
    confidenceScore: bigint;
}
export interface AnalysisRecord {
    id: AnalysisId;
    userId: UserId;
    explanation: string;
    isFake: boolean;
    reviewText: string;
    confidenceScore: bigint;
    timestamp: Timestamp;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PaginatedAnalysesV2 {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<AnalysisRecordV2>;
}
export type AnalysisId = bigint;
export interface AnalysisResult {
    explanation: string;
    isFake: boolean;
    confidenceScore: bigint;
    timestamp: Timestamp;
}
export interface DashboardStatsV2 {
    totalAnalyses: bigint;
    imageCount: bigint;
    fakeCount: bigint;
    recentAnalyses: Array<AnalysisRecordV2>;
    urlCount: bigint;
    textCount: bigint;
    genuineCount: bigint;
    averageScore: bigint;
}
export enum AnalysisType {
    URL = "URL",
    Text = "Text",
    Image = "Image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    analyzeImage(imageKey: string): Promise<ImageAnalysisResult>;
    analyzeProductUrl(url: string): Promise<UrlAnalysisResult>;
    analyzeReview(reviewText: string): Promise<AnalysisResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearMyAnalyses(): Promise<void>;
    deleteAnalysis(analysisId: AnalysisId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDashboardStatsV2(): Promise<DashboardStatsV2>;
    getMyAnalyses(page: bigint, pageSize: bigint): Promise<PaginatedAnalyses>;
    getMyAnalysesV2(page: bigint, pageSize: bigint, analysisType: AnalysisType | null): Promise<PaginatedAnalysesV2>;
    isCallerAdmin(): Promise<boolean>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    transformV2(input: TransformationInput): Promise<TransformationOutput>;
}
import type { AnalysisId as _AnalysisId, AnalysisRecordV2 as _AnalysisRecordV2, AnalysisType as _AnalysisType, DashboardStatsV2 as _DashboardStatsV2, PaginatedAnalysesV2 as _PaginatedAnalysesV2, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async analyzeImage(arg0: string): Promise<ImageAnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeImage(arg0);
            return result;
        }
    }
    async analyzeProductUrl(arg0: string): Promise<UrlAnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeProductUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeProductUrl(arg0);
            return result;
        }
    }
    async analyzeReview(arg0: string): Promise<AnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeReview(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearMyAnalyses(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyAnalyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyAnalyses();
            return result;
        }
    }
    async deleteAnalysis(arg0: AnalysisId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDashboardStatsV2(): Promise<DashboardStatsV2> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStatsV2();
                return from_candid_DashboardStatsV2_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStatsV2();
            return from_candid_DashboardStatsV2_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAnalyses(arg0: bigint, arg1: bigint): Promise<PaginatedAnalyses> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAnalyses(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAnalyses(arg0, arg1);
            return result;
        }
    }
    async getMyAnalysesV2(arg0: bigint, arg1: bigint, arg2: AnalysisType | null): Promise<PaginatedAnalysesV2> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAnalysesV2(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PaginatedAnalysesV2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAnalysesV2(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PaginatedAnalysesV2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async transformV2(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformV2(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformV2(arg0);
            return result;
        }
    }
}
function from_candid_AnalysisRecordV2_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisRecordV2): AnalysisRecordV2 {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisType): AnalysisType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStatsV2_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStatsV2): DashboardStatsV2 {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedAnalysesV2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedAnalysesV2): PaginatedAnalysesV2 {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_AnalysisRecordV2>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<AnalysisRecordV2>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n7(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAnalyses: bigint;
    imageCount: bigint;
    fakeCount: bigint;
    recentAnalyses: Array<_AnalysisRecordV2>;
    urlCount: bigint;
    textCount: bigint;
    genuineCount: bigint;
    averageScore: bigint;
}): {
    totalAnalyses: bigint;
    imageCount: bigint;
    fakeCount: bigint;
    recentAnalyses: Array<AnalysisRecordV2>;
    urlCount: bigint;
    textCount: bigint;
    genuineCount: bigint;
    averageScore: bigint;
} {
    return {
        totalAnalyses: value.totalAnalyses,
        imageCount: value.imageCount,
        fakeCount: value.fakeCount,
        recentAnalyses: from_candid_vec_n7(_uploadFile, _downloadFile, value.recentAnalyses),
        urlCount: value.urlCount,
        textCount: value.textCount,
        genuineCount: value.genuineCount,
        averageScore: value.averageScore
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnalysisId;
    userId: _UserId;
    analysisType: _AnalysisType;
    explanation: string;
    isFake: boolean;
    reviewText: string;
    sourceUrl: [] | [string];
    confidenceScore: bigint;
    imageKey: [] | [string];
    timestamp: _Timestamp;
}): {
    id: AnalysisId;
    userId: UserId;
    analysisType: AnalysisType;
    explanation: string;
    isFake: boolean;
    reviewText: string;
    sourceUrl?: string;
    confidenceScore: bigint;
    imageKey?: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        userId: value.userId,
        analysisType: from_candid_AnalysisType_n10(_uploadFile, _downloadFile, value.analysisType),
        explanation: value.explanation,
        isFake: value.isFake,
        reviewText: value.reviewText,
        sourceUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.sourceUrl)),
        confidenceScore: value.confidenceScore,
        imageKey: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.imageKey)),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    URL: null;
} | {
    Text: null;
} | {
    Image: null;
}): AnalysisType {
    return "URL" in value ? AnalysisType.URL : "Text" in value ? AnalysisType.Text : "Image" in value ? AnalysisType.Image : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisRecordV2>): Array<AnalysisRecordV2> {
    return value.map((x)=>from_candid_AnalysisRecordV2_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisType): _AnalysisType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisType | null): [] | [_AnalysisType] {
    return value === null ? candid_none() : candid_some(to_candid_AnalysisType_n14(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisType): {
    URL: null;
} | {
    Text: null;
} | {
    Image: null;
} {
    return value == AnalysisType.URL ? {
        URL: null
    } : value == AnalysisType.Text ? {
        Text: null
    } : value == AnalysisType.Image ? {
        Image: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
